# $Id: Makefile,v 1.1 2005/07/25 05:52:00 magicyang Exp $
#
# Digest Authentication - Database support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=auth_db.so
LIBS=

include ../../Makefile.modules
