# $Id: Makefile,v 1.1 2005/07/25 05:52:09 magicyang Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=xlog.so
LIBS=

include ../../Makefile.modules
