# $Id: Makefile,v 1.1 2005/07/25 05:52:04 magicyang Exp $
#
# Presence Agent
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=pa.so
LIBS=

include ../../Makefile.modules
