# $Id: Makefile,v 1.1 2005/07/25 05:52:01 magicyang Exp $
#
# exec module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=exec.so
LIBS=

include ../../Makefile.modules
