# $Id: Makefile,v 1.1 2005/07/25 05:52:01 magicyang Exp $
#
# database example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=dbtex.so
LIBS=

include ../../Makefile.modules
