# $Id: Makefile,v 1.1 2005/07/25 05:52:01 magicyang Exp $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

# extra debug messages
DEFS+=-DDBT_EXTRA_DEBUG
 
include ../../Makefile.defs
auto_gen=
NAME=dbtext.so
LIBS=

include ../../Makefile.modules
