#!/usr/bin/perl

# $RCSfile: ADB,v $$Revision: 1.2 $$Date: 2005/07/25 04:55:43 $

# This script is only useful when used in your crash directory.

$num = shift;
exec 'adb', '-k', "vmunix.$num", "vmcore.$num";
