# $Id: Makefile,v 1.5 2005/08/12 03:33:22 magicyang Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
