# $Id: Makefile,v 1.1 2005/07/25 05:52:00 magicyang Exp $
#
# Digest Authentication - Diameter support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=auth_diameter.so
#LIBS=-Llib -ldiameter_msg
#LIBS=-L$(LOCALBASE)/lib -L/usr/pkg/lib -lradiusclient

include ../../Makefile.modules
