#
# pppstats Makefile for SVR4 systems
# $Id: Makefile.svr4,v 1.2 2005/07/25 04:59:40 magicyang Exp $
#

include ../svr4/Makedefs

CFLAGS = -DSTREAMS -I../include $(COPTS)

all: pppstats

pppstats: pppstats.c
	$(CC) $(CFLAGS) -o pppstats pppstats.c

install: pppstats
	$(INSTALL) -f $(BINDIR) pppstats
	$(INSTALL) -m 444 -f $(MANDIR)/man8 pppstats.8

clean:
	rm -f pppstats *~ core
