#
# libposix makefile
# $Id: Makefile,v 1.2 2005/07/25 04:59:38 magicyang Exp $
#

ARCHFLAGS = 

SRCS = libposix.c
OBJS = libposix.o

CFLAGS = -O -D_POSIX_SOURCE $(ARCHFLAGS)

all: $(OBJS)

clean:
	rm -f *.o *~ core

