# $Id: Makefile,v 1.1 2005/07/25 05:51:59 magicyang Exp $
#
# auth example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=auth.so
LIBS=

include ../../Makefile.modules
