# $Id: Makefile,v 1.1 2005/07/25 05:52:07 magicyang Exp $
#
# print example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=textops.so
LIBS=

include ../../Makefile.modules

